export const DAMAGE_ANIMATION_DURATION_MS = 2000;
export const DAMAGE_ANIMATION_FADE_START_RATIO = 0.75;
export const DAMAGE_ANIMATION_FADE_DELAY_MS =
  DAMAGE_ANIMATION_DURATION_MS * DAMAGE_ANIMATION_FADE_START_RATIO;
export const DAMAGE_ANIMATION_FADE_DURATION_MS =
  DAMAGE_ANIMATION_DURATION_MS - DAMAGE_ANIMATION_FADE_DELAY_MS;
